title: DAVCast
description: WebDAV file manager and media browser for iPhone and iPad
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
header_pages:
  - index.md
  - support.md
  - privacy-policy.md
  - terms.md
  - app-store-connect.md